### ISSUE TITLE
json for canticristiani integration

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#13]
Salva le tabelle in json e includi l'id_canti per Michele

To do:

- [x] add `data` key
- [ ] improve `data` key using calendario liturgie

**Comment by dennisangemi** [comment]
Ciao @mamminim, ho preparato dei json che puoi cominciare a testare e ho reso il repo pubblico così puoi importarli senza token. Questi sono i path attraverso cui puoi accedere sempre all'ultima versione

```
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-top20-latest.json
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-ingresso-latest.json
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-offertorio-latest.json
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-comunione-latest.json
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-congedo-latest.json
```

Fammi sapere se è ok oppure preferisci avere/rimuovere dei campi

**Comment by mamminim** [comment]
Ciao @dennisangemi 

direi sicuramente di aggiungere la data.

Poi, metterei tutto insieme in un solo json aggiungendo due campi momento_main per indicare Ingresso, offertorio, comunione, fine e la data della celebrazione, come indicato qui sotto

```
    {
        "id_canti": 2647,
        "similarity": 28,
        **"data": "2024-06-03",
        "momento_main": 21,**
        "titolo": "La sua casa",
        "autore": "Francesco Buttazzo",
        "raccolta": "Guidati nel deserto",
        "momento": "21,10",
        "link_youtube": "aZB9J7PpAmicltm6",
        "titolo_md": "[La sua casa](https:\/\/www.youtube.com\/watch?v=aZB9J7PpAmicltm6)"
    },
```

**Comment by dennisangemi** [comment]
Ciao @mamminim, non ho capito bene cosa si intende per `momento_main`.

Attualmente, se ci fai caso, alcuni canti di ingresso ad esempio non sono presenti nel top20 semplicemente perchè prendo i primi 20 di tutti quelli consigliati per generare il file top20.

Per generare il file ingresso, invece, filtro il dataset di tutti i canti consigliati selezionando solo i canti che tra i momenti hanno l'ingresso, ordino per similarità, seleziono solo i primi 10. Procedimento analogo per gli altri momenti

**Comment by dennisangemi** [comment]
Ciao @mamminim, con l'ultimo commit ho aggiunto la data. Per adesso è la data della prossima domenica (e non la data della prossima celebrazione domenicale o festiva secondo il calendario). Perfezionerò in seguito

**Comment by mamminim** [comment]
Ciao Dennis,

ti chiedevo di fare una unica url dove si indicava con moment_main se un
canto fosse di ingresso, offertorio, comunione o congedo.
Tengo separati i 4 file e il momento_main lo ricavo da questa tua
suddivisione. dimentica quindi la richiesta del momento main che ti ho
fatto in precedenza

Mi sembra però che qualcosa non stia funzionando.... la variabile
similarity ad esempio di questo file
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-ingresso-latest.json
è sempre 0.

Mi fai sapere?


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno lun 24 giu 2024 alle ore 01:36 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Ciao @mamminim, se vuoi ti posso dare un unico file con la top40 e poi operi i filtri a te utili. È una cosa fattibile secondo te?

Per quanto riguarda la similarità 0, è accaduto perchè la pagina della liturgia cei della prossima domenica è vuota: https://www.chiesacattolica.it/liturgia-del-giorno/?data-liturgia=20240630. Altro motivo per provare a staccarci da questi servizi esterni da cui peschiamo le liturgie hah

**Comment by mamminim** [comment]
Ciao Dennis,

questa mattina ho terminato lo script che legge dai tuoi output (json) e
inserisce in 2 tabelle: app_cantisuggeriti e app_calendario_liturgico
Per i canti suggeriti, ho preso in considerazione solo i seguenti:

   -
   https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-ingresso-latest.json
   -
   https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-offertorio-latest.json
   -
   https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-comunione-latest.json
   -
   https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggeriti-congedo-latest.json

Mentre per il calendario liturgico questo output:
https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/calendari_liturgici/calendario_2019-2050.json

Ora devo configurare il crontab per automatizzare la procedura e ti chiedo:
Quando vengono aggiornati i "nuovi" suggeriti?
Il calendario liturgico 2019-2050 viene mai aggiornato in automatico?

Ora nei prossimi giorni provo a realizzare una nuova sezione del sito
denominata suggeriti.

Ti tengo aggiornato

Michele.

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno lun 24 giu 2024 alle ore 11:24 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Ciao @mamminim, ottimo!

> Quando vengono aggiornati i "nuovi" suggeriti?

Ogni lunedì a mezzanotte. Questo è il cron:

https://github.com/dennisangemi/hildegard/blob/d551fb76e67b9afb866d31e0c5afc03888bffb36/.github/workflows/suggeritore.yml#L7

> Il calendario liturgico 2019-2050 viene mai aggiornato in automatico?

Attualmente no. Per ottenerlo così come serviva a noi ho fatto un po' di lavoro e pulizia manuale che non ho reso riproducibile con uno script. Se pensi possa essere utile avere degli aggiornamenti (magari per via di update comunicati tramite api), posso provare senza problemi a realizzare qualche script. Che dici?

**Comment by mamminim** [comment]
Ok grazie per le info.

Adesso metto il cron sul server e poi se i dati sono aggiornati il prossimo
martedì mattina (vedo di avere anche la tabella che mostra i suggerimenti.

Relativamente al calendario liturgico, l'unica cosa che mi potrebbe
interessare è l'aggiornamento di liturgia1 e liturgia2 nel caso questi
siano aggiornati.

Grazie, Michele


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno mer 26 giu 2024 alle ore 14:40 Dennis Angemi <
***@***.***> ha scritto:

**Comment by mamminim** [comment]
Scusami Dennis,

mi sai anche dire che faccio a prendere lo storico dei canti suggeriti?

Michele

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno mer 26 giu 2024 alle ore 14:44 Michele Mammini ***@***.***>
ha scritto:

**Comment by dennisangemi** [comment]
> Relativamente al calendario liturgico, l'unica cosa che mi potrebbe
interessare è l'aggiornamento di liturgia1 e liturgia2 nel caso questi
siano aggiornati.

Se vuoi, ci inventiamo un modo per aggiornarlo periodicamente (anche solo per le key liturgia1,2). 

Considera anche che, se vogliamo, ci possiamo anche staccare totalmente da questi link esterni e sfruttare le liturgie che ho estratto dai lezionari. Il link per ottenerle è questo:

https://raw.githubusercontent.com/dennisangemi/hildegard/main/risorse/lezionari/liturgie/C1-A.txt

Basta cambiare l'id alla fine del link e potrai accedere a tutte le 250 circa liturgie. 

Bisogna solo pulirle un pochino

**Comment by dennisangemi** [comment]
> mi sai anche dire che faccio a prendere lo storico dei canti suggeriti?

Ci sono due modi:

1. Sfrutti i csv che hanno questa struttura e la data alla fine 

https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/suggerimenti-2024-06-30.csv

2. Accedi al log delle modifiche del file json che usi normalmente. Github registra tutte le versioni e ti consente di scaricarle tutte. Non sono molto esperto ma se cerchi online trovi sicuramente qualcosa per scaricare tutte le versioni 

Ovviamente, rimango disponibile per altre strade e sono aperto ai tuoi suggerimenti ;)

Cc @mamminim

**Comment by mamminim** [comment]
Buongiorno Dennis,

a questo link https://www.librettocanti.it/suggerimenti, una prima versione
della pagina dei suggerimenti.
Se per te va bene la posso rendere pubblica creando un menu che metterei
accanto a quello dei canti.

Relativamente alle richieste degli ultimi giorni, vedo se riesco a gestirle
nel weekend

A presto,

Michele.


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno mer 26 giu 2024 alle ore 19:32 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Buongiorno @mamminim, grazie!
Che bello!

Mi sembra perfetto. 

Due sole osservazioni:
1. Adesso che ho visto l'output della tua tabella ho capito cosa intendevi. Se vuoi, posso costruire un unico json così eviti di importarne 4
2. Il testo è linkato al file markdown che c'è in questo repo oppure è hardcoded? Chiedo solo perché in futuro, quando miglioreremo l'algoritmo di selezione, immagino che modificherò il testo.

Grazie ancora e che bella questa collaborazione!

**Comment by mamminim** [comment]
Ok, quindi posso metterlo disponibile agli utenti.

Per me va bene anche 4 file. In questo modo gli assegno il momento
principale identificato proprio dal nome del json.
Il testo associato è scritto direttamente nel codice della pagina. Se lo
modifichi (per ora) non fai altro che comunicarmelo ed io lo aggiorno

Grazie a te,
avevo bisogno di qualcuno con idee nuove che facesse in qualche modo
evolvere il progetto!

Michele.


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno ven 28 giu 2024 alle ore 10:19 Dennis Angemi <
***@***.***> ha scritto:

**Comment by mamminim** [comment]
Ho reso la pagina visualizzabile a tutti gli utente e in HP del sito la
*news*

Ancora grazie e una buona giornata, Michele.

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno ven 28 giu 2024 alle ore 11:07 Michele Mammini ***@***.***>
ha scritto:

**Comment by dennisangemi** [comment]
Che bello @mamminim! Sono felice ;)

Allora chiudo questa issue. 

P.s.
Non sarebbe carino anche mostrare direttamente nella pagina dei suggerimenti l'ultima versione della tabella senza fare click sull'archivio?
