### ISSUE TITLE
[api cantictistiani] fix and activate db downloader

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#16]
- [x] aggiungere secrets e variabili di ambiente per `USERNAME` e `PASSWORD` per richiedere token
- [x] attendere implementazione autenticazione
- [x] aggiornare script meccanismo di autenticazione
- [x] testare action
- [x] attivare action per aggiornare canti e anagrafica una volta al mese

**Comment by mamminim** [comment]
senza autenticazione non dovresti essere più in grado di prendere i canti.
forse ti è rimasta aperta?

**Comment by dennisangemi** [comment]
Ciao @mamminim, sisi mi è rimasta aperta perchè non ci ho più lavorato. Mi confermi che hai implementato l'autenticazione anche per la chiamata che sfruttavo per ottenere il testo dei canti? Posso procedere a modificare gli script aggiugendo autenticazione?

**Comment by mamminim** [comment]
Certo puoi procedere. Non credo che se lo chiami senza autenticazione, ti
ritorni il json del canti

Michele

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno dom 23 giu 2024 alle ore 20:38 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Ciao @mamminim, ho aggiunto autenticazione e tutto funziona. Grazie mille!!! Ho già testato l'action che gira su github: impiega circa 15min per scaricare tutti i canti (tantissimo! magari in futuro proviamo a fare qualcosa per migliorare la velocità).

Qui trovi il report del run https://github.com/dennisangemi/hildegard/actions/runs/9643677249/job/26594168635
![image](https://github.com/dennisangemi/hildegard/assets/77018886/ec8d5709-df76-442e-aaa2-fb8775c0c8b0)

Attualmente ho impostato l'esecuzione automatica ogni primo giorno del mese. Come ti sembra questa condizione?
