### ISSUE TITLE
[improvements] canticristiani history

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#17]
Michele Mammini dispone dello storico dei canti suonati a partire dalle statistiche di canticristiani. Si potrebbe, con la disponibilità di Michele, considerare questa "cronologia" come una nuova fonte dati da affiancare a quelle esistenti in hildegard per migliorarne l'accuratezza (vd #19).

<details>
<summary>Old issue</summary>
Michele di canticristiani potrebbe metterci a disposizione anche la "cronologia" dei canti suonati nei festivi e il numero di dispositivi attivi. Bisogna capire bene come poter sfruttare questi dati.

Se per le "medesime domeniche" si rivelano essere adatti gli stessi canti allora è facile. Michele ha già tutto (!) e io potrei occuparmi di calcolare uno score che tenga conto sia della similarità che dello storico dei canti suonati. 

Dopo aver effettuato il join dei dati, **normalizzato** la similarità e i counts dei canti suonati, potremmo calcolare la **media pesata** (che sarà il nostro score) e poi tradurre lo score in una scala di **adeguatezza** così definita

- ✅ Alta: se il canto è collocato nel terzo quartile di similarità e se è stato suonato da più del 60% dei dispositivi (?);
- 👌 Discreta: discreta quando (si trova nel terzo quartile o è stato suonato da più del 60% dei dispositivi) e la media pesata si trova nel terzo quartile;
- 👍 Buona: quando non si ricade in nessuno dei casi precedenti ma comunque la media pesata è buona (>70)

Se, sperimentando, si vede che tutti i canti selezionati rientrano nella categoria alta allora si può essere più restrittivi coi parametri: 
- terzo quartile (75%) -> 90%
- 60% dei suonati -> 75%

e così via.

Questa è la distribuzione della similarità evidentemente normale
![image](https://github.com/dennisangemi/hildegard/assets/77018886/ed3406a6-65c8-4d23-8b4c-87d2ba8e034b)
</details>

**Comment by dennisangemi** [comment]
Ciao @mamminim, riflettevo sullo storico dei canti suonati e pensavo che non ha molto senso consigliare gli stessi canti che sono stato suonati nelle medesime domeniche. Perché? Basta pensare a Chiamati per nome che è in "vetta alle classifiche" da settimane nonostante la sua adeguatezza non sia sempre proporzionale al numero di volte in cui è stato suonato. 

Per ovviare a questo problema, si dovrebbe in qualche modo rimuovere il "rumore di fondo" costituito dai canti che vengono suonati spesso/quasi sempre e che non contribuiscono a migliorare l'accuratezza dell'attuale output di hildegard. 

Forse ho trovato una soluzione! Basterebbe calcolare la media del numero di volte in cui un canto è stato suonato, per ogni canto (indipendentemente dalle domeniche). In questo modo, di domenica in domenica, posso calcolare lo scarto dalla media. I canti con lo scarto maggiore sono quelli che NON vengono suonati tutte le domeniche e che quindi sono stati scelti dagli animatori per questioni legate all'aderenza alla liturgia.

Per riuscire a fare una cosa del genere, ti chiederei cortesemente la possibilità di accedere allo storico dei canti suonati. 

Mi basterebbe un'api, un file csv, un file json, qualsiasi cosa, che contenga queste informazioni: data della domenica (o del festivo, solennità, bla bla), id del canto, numero di volte in cui è stato suonato. 

Pensi sia una cosa fattibile? Grazie in anticipo! @mamminim

**Comment by dennisangemi** [comment]
Sera @mamminim, in questi giorni sono stato un po' febbricitante e sono riuscito a lavorare a hildegard. Ho incluso lo storico dei canti suonati nel calcolo dell'adeguatezza! Adesso nel sito troverai una percentuale di adeguatezza e anche un'etichetta (alta, buona, ecc). 

Dovrei essere stato in grado di riflettere la nuova adeguatezza anche nei json che usi tu. Ti pregherei però di controllare se la struttura è rimasta inalterata.

p.s.
ti va se nei json includo la label di adeguatezza (alta, buona, mh) così magari la puoi aggiungere alla sezioni suggerimenti del tuo sito?

Grazie sempre di tuttooo!!!

**Comment by mamminim** [comment]
Ciao Dennis,

aggiungi pure. Io dovrei importare solo determinati campi, quindi è
sufficiente che questi non cambino nome.
Appena posso integro con la nuova label adeguatezza

Grazie a te!

Michele

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno mar 22 ott 2024 alle ore 23:47 Dennis Angemi <
***@***.***> ha scritto:
