### ISSUE TITLE
calendario liturgico

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#18]
Può essere molto utile implementare questo tool https://www.favrin.net/misc/calendario_liturgico/sviluppatori.html

one liner utili

```sh
# scarica il csv dell'intero calendario liturgico di un dato anno
curl -kL "https://www.favrin.net/misc/calendario_liturgico/?anno=2024&intervallo=anno&nofc=1&nolink=1&&output=json" | jq "[.eventi[] | {giorno, mese, anno, ts, evento, tipo_evento}]" | mlr --j2c cat
```

a questa tabella si può aggiungere il giorno corrispondente alla data e selezionare così tutte le domeniche

**Comment by mamminim** [comment]
Queste API sono proprio quello che ci serve.

Vedo di fare un piccolo tool che elabora queste informazioni e le inserisce
in una tabella.
Poi facciamo una API che te le mostra, che ne dici?

Michele


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno dom 2 giu 2024 alle ore 19:28 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Ciao Michele, ieri sera ci ho cominciato a giocare anche io.

Ora ti incollo un po' di codice che scarica i calendari fino al 2050 e
pulisce un po' il dataset. Se vuoi, ti posso fornire un csv esattamente con
la struttura della tabella che ti serve per importarla nel tuo db.

Magari però stavolta ti vuoi staccare dal modello della tabella statica che
contiene le festività e vuoi chiamare l'api ogni volta che ti serve

Il Lun 3 Giu 2024, 07:50 Michele Mammini ***@***.***> ha
scritto:

**Comment by mamminim** [comment]
Ciao Dennis,

mandami sempre il dataset in json che lo preferisco.
Poi tendo a storicizzare per non incorrere nel rischio che il servizio
venga interrotto.

Michele


--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno lun 3 giu 2024 alle ore 10:57 Dennis Angemi <
***@***.***> ha scritto:

**Comment by dennisangemi** [comment]
Ciao @mamminim

- qui lo script https://github.com/dennisangemi/hildegard/blob/main/scripts/get_calendario_liturgico
- qui l'output in json https://raw.githubusercontent.com/dennisangemi/hildegard/main/data/calendari_liturgici/joined.json

fammi sapere come modificare la struttura del file per consentirti di importarlo nella tua tabella `anno_liturgico`

**Comment by dennisangemi** [comment]
Comunque @mamminim pensavo che se non vuoi riadattare (ai nuovi dati) le tue api che selezionano i canti già suonati per un dato giorno, potremmo trovare un modo che mi consenta di accedere a un file che contiene lo storico dei canti suonati e poi seleziono io le date antecedenti nel momento in cui viene lanciato il suggeritore. Fammi sapere quale soluzione ti è più comoda ;)

**Comment by dennisangemi** [comment]
p.s. se il calendario ti sembra ok, chiuderei pure questa issue. Lascio a te

**Comment by mamminim** [comment]
Riusciamo ad aggiungere i link a liturgia1 e liturgia2 presente negli eventi dell'api ?
```
https://www.favrin.net/misc/calendario_liturgico/?anno=2024&output=json
```

**Comment by dennisangemi** [comment]
Ciao @mamminim, ho aggiunto i link di `liturgia1` e `liturgia2` che torna l'api. I link dei file rimangono gli stessi che ti ho indicato [qui](https://github.com/dennisangemi/hildegard/issues/18#issuecomment-2150967258) (se dovessero cambiare a causa di alcune riorganizzazione di questa repo, ti avviserò)

A occhio noto come per alcuni anni entrambi i campi siano vuoti (ad esempio per il 2050). 

Questo problema ovviamente si può aggirare costruendoci le nostre liturgie (dato che adesso abbiamo [l'anagrafica ](https://github.com/dennisangemi/hildegard/blob/main/liturgie/lezionari/anagrafica_liturgie_cei.csv)che ho estratto dai lezionari della CEI). Richiederà un po' di tempo ma forse vale la pena lavorarci appena finiamo di implementare la versione base di questo progetto. In questo modo riusciremo ad essere totalmente indipendenti dai siti che pubblicano la liturgia (cei, la chiesa, la parola, bla bla bla).

Fammi sapere se i file sono ok e sorry per il ritardo ;)

Lascio a te la chiusura di questa issue
