### ISSUE TITLE
custom domain reset on every build

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#25]
Ciao @aborruso, sono costretto ad invocare i tuoi poteri.

Per caso ti è mai capitato che il tuo custom domain venisse "cancellato" dalla pagina delle impostazioni di pages a seguito di ogni build di mkdocs? 

![Screenshot_20240624_023925_Chrome](https://github.com/dennisangemi/hildegard/assets/77018886/02bc550e-9715-4055-bc6b-0a07b3613bce)

È abbastanza snervante perché in sostanza il collegamento a hildegard.it si rompe ogni settimana :/

Ho provato a [googlare](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://github.com/tschaub/gh-pages/issues/236&ved=2ahUKEwj_3snH_fKGAxXr9AIHHYUvB7sQFnoECBMQAQ&usg=AOvVaw1jhNp9q7g1BDsKnm18V3Oq) e alcuni sostengono sia un problema di CNAME ma i miei file mi sembrano a posto :( 

Per caso hai qualche idea? Grazie e sorry per il disturbo!

**Comment by dennisangemi** [comment]
Update: credo che a ogni build venga cancellato il CNAME del branch gh-pages. Aggiungere il custom domain name nella pagina delle impostazioni credo equivalga al commit del CNAME

**Comment by aborruso** [comment]
Ciao caro,
devi mettere il CNAME in docs, come in
https://github.com/aborruso/arigadicomando/tree/master/docs

In modo che sia pubblicato a ogni modifica. 

Baci

**Comment by dennisangemi** [comment]
Ovviamente ha funzionato! Grazie mille @aborruso, sei sempre preziosissimo <3
