### ISSUE TITLE
add link to accordi

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#5]
basta usare l'id. togliere url youtube e mettere link a librettocanti

**Comment by dennisangemi** [comment]
Ciao @mamminim, mi piacerebbe linkare i titoli dei canti nelle tabelle di hildegard agli accordi che pubblichi in canticristiani o librettocanti (in questo modo dovremmo anche riuscire a migliorare seo). 

Attualmente mi pare di capire che l'url base per accedere alla pagina di un canto è il seguente:
- https://www.librettocanti.it/mod_canti_gestione#!canto/vedi/1634/a-te-grido-mio-signore
- https://app.canticristiani.it/#!canto/a-te-grido-mio-signore/1634/0

Ti chiedo: esiste un path più semplice che mi consente di sfruttare solo l'id del canto senza lo slug del titolo? es. https://www.librettocanti.it/vedi/1634 oppure https://app.canticristiani.it/#!canto/1634 o qualsiasi altra cosa simile

Se non esiste, pensi sia possibile implementare anche solo un sistema di redirect? Oppure forse è più facile che io inserisca un metodo per creare gli slug a partire dai titoli delle canzoni? tu come li costruisci?

**Comment by dennisangemi** [comment]
@mamminim questa issue non è prioritaria. Ho pensato che posso accedere rapidamente ai link facendo scraping di questa pagina https://www.librettocanti.it/mod_canti_gestione e non dovrei metterci tanto tempo. Non c'è bisogno che attivi redirect se già non esiste ;)

**Comment by mamminim** [comment]
Ciao Dennis,

ho aggiunto due nuove rotte di Navigo (js) per far si che il canto sia
visibile anche secondo questa logica:

https://www.librettocanti.it/mod_canti_gestione#!canto/vedi/1634

senza lo slug che determino con questa funzione js:

function slugify(text) {
return text.toString().toLowerCase().trim()
.normalize('NFD') // separate accent from letter
.replace(/[\u0300-\u036f]/g, '') // remove all separated accents
.replace(/\s+/g, '-') // replace spaces with -
.replace(/&/g, '-and-') // replace & with 'and'
.replace(/[^\w\-]+/g, '') // remove all non-word chars
.replace(/\-\-+/g, '-') // replace multiple '-' with single '-'
}

Michele

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno ven 28 giu 2024 alle ore 12:31 Dennis Angemi <
***@***.***> ha scritto:

**Comment by mamminim** [comment]
Ho fatto velocemente anche questo percorso, ma ci dovrei lavorare ancora
perchè dovrei cambiare tutta la logica che ci sta dietro.

https://www.librettocanti.it/canti#!canto/vedi/2/abba-padre-ascoltami

mi piacerebbe farlo diventare:

https://www.librettocanti.it/canti/2/accordi/abba-padre-ascoltami
https://www.librettocanti.it/canti/2/testo/abba-padre-ascoltami

Michele

--

*Michele MamminiConsulenze Informatiche di Michele Mammini*
*P.I. 02143100507*




* Mobile: +39 328 9039640 email: ***@***.*** ***@***.***>
Skype: mamminim*


--------------
Ai sensi del D.Lgs 196/03 si precisa che le informazioni contenute in
questo messaggio sono da considerarsi riservate e ad uso esclusivo del
destinatario.
Qualora il messaggio le fosse pervenuto per errore, La preghiamo di
eliminarlo senza copiarlo e non inoltrarlo a terzi dandocene gentilmente
comunicazione.


Il giorno ven 28 giu 2024 alle ore 17:01 Michele Mammini ***@***.***>
ha scritto:

**Comment by dennisangemi** [comment]
Grazie mille @mamminim, questa è sicuramente la soluzione più solida (lo scraping non lo sarebbe stato!)

Ti aggiorno quando linkerò le tabelle ai tuoi canti!

P.s.
Mi piace tantissimo la coerenza che sta dietro a
https://www.librettocanti.it/canti/2/accordi/abba-padre-ascoltami
https://www.librettocanti.it/canti/2/testo/abba-padre-ascoltami

Se mai dovessi cambiare in futuro l'url per accedere alla pagina del canto tramite solo id, lemme know

Grazie ancora!
